services:
  drathos-backend:
    container_name: drathos-backend
    image: valt1n/drathos-backend:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - API_PORT=5001
      - MONGODB_URI=mongodb://mongodb:27017/drathos
      - JWT_TOKEN=hide_this
      - CORS_STRICT_MODE=false
      - CORS_ALLOWED_ORIGINS=*
      - GAME_FILES_DIR=/usr/src/app/serverData/serverGames
      - MOD_FILES_DIR=/usr/src/app/serverData/serverMods
      - TWITCH_CLIENT_ID=YOUR_TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET=YOUR_TWITCH_CLIENT_SECRET
    ports:
      - "8080:5001"
    volumes:
      - server-data:/usr/src/app/serverData
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - traefik_network
      - drathos_network
    ## Traefik Labels
    labels:
      - "traefik.enable=true"
      - "tag=app-external"
      # Web interface accessible on the same domain
      - "traefik.http.routers.drathos-backend.rule=Host(`drathos.home.arpa`)"
      - "traefik.http.routers.drathos-backend.entrypoints=https"
      - "traefik.http.routers.drathos-backend.service=drathos-backend"
      - "traefik.http.services.drathos-backend.loadbalancer.server.port=5001"
      - "traefik.http.routers.drathos-backend.tls=true"
      - "traefik.http.routers.drathos-backend.tls.certresolver=stepca"
      # Disable buffering for large downloads
      - "traefik.http.middlewares.nobuffering.buffering.maxRequestBodyBytes=0"
      - "traefik.http.middlewares.nobuffering.buffering.maxResponseBodyBytes=0"
      - "traefik.http.middlewares.nobuffering.buffering.memRequestBodyBytes=0"
      - "traefik.http.middlewares.nobuffering.buffering.memResponseBodyBytes=0"
      - "traefik.http.routers.drathos-backend.middlewares=nobuffering"

  mongodb:
    container_name: drathos-db
    image: mongo:4
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - drathos_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongo-data:
  server-data:

networks:
  traefik_network:
    external: true
  drathos_network:
    external: true
